# Generated by Django 2.0.6 on 2018-07-11 09:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('purchase', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='purchase',
            name='buyer_location',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='purchase',
            name='buyer_name',
            field=models.CharField(max_length=30),
        ),
        migrations.AlterField(
            model_name='purchase',
            name='buyer_phone_number',
            field=models.CharField(max_length=20),
        ),
    ]
